apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
  namespace: demokubernetes
spec:
  serviceAccountName: jenkins
  containers:
  - name: test-container
    image: busybox
    command: ['sleep', '3600']
